apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-secret: basic-auth-secret
    nginx.ingress.kubernetes.io/auth-type: basic
  name: alarm
  namespace: monitoring
spec:
  ingressClassName: nginx
  tls:
    - secretName: monitoring-certs
  rules:
  - host: alarm-i7oqvu.yun-paas.com
    http:
      paths:
      - backend:
          service:
            name: alertmanager-operated
            port: 
              number: 9093
        path: /
        pathType: ImplementationSpecific
