apiVersion: extensions/v1beta1
kind: Ingress
metadata:
   name: alarm
   namespace: monitoring
spec:
   ingressClassName: nginx
   tls:
     - secretName: monitoring-certs
   rules:
   - host: k8s.alarm
     http:
       paths:
       - path: /
         backend:
          serviceName: alertmanager-operated
          servicePort: 9093
