apiVersion: extensions/v1beta1
kind: Ingress
metadata:
   name: grafana
   namespace: monitoring
spec:
   ingressClassName: nginx
   tls:
     - secretName: monitoring-certs
   rules:
   - host: k8s.grafana
     http:
       paths:
       - path: /
         backend:
          serviceName: grafana
          servicePort: 3000
