apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: logging
spec:
  tls:
    - secretName: logging-certs
  rules:
  - host: kibana-3ulvuv.yun-paas.com
    http:
      paths:
      - backend:
          service:
            name: kibana
            port:
              number: 5601
        path: /
        pathType: ImplementationSpecific